name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: openknowledge/ckan-dev:2.9
    services:
      solr:
        image: ckan/ckan-solr:2.9-solr8
      postgres:
        image: ckan/ckan-postgres-dev:2.9
        env:
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
          POSTGRES_DB: keycloak
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3
      keycloak:
        image: bitnami/keycloak:16.1.1
        env:
          KEYCLOAK_ADMIN_USER: admin
          KEYCLOAK_ADMIN_PASSWORD: password
          KEYCLOAK_DATABASE_HOST: postgres
          KEYCLOAK_DATABASE_PORT: 5432
          KEYCLOAK_DATABASE_NAME: keycloak
          KEYCLOAK_DATABASE_USER: keycloak
          KEYCLOAK_DATABASE_PASSWORD: keycloak
        options: >-
          --health-cmd "curl -f http://localhost:8080/auth/realms/master || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8080:8080
    env:
      CKAN_SQLALCHEMY_URL: postgresql://keycloak:keycloak@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://keycloak:keycloak@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://keycloak:keycloak@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      KEYCLOAK_URL: http://keycloak:8080
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install -e .
    - name: Wait for PostgreSQL
      run: |
        until PGPASSWORD=keycloak psql -h postgres -U keycloak -d keycloak -c '\q'; do
          >&2 echo "PostgreSQL is unavailable - sleeping"
          sleep 1
        done
    - name: Wait for Keycloak
      run: |
        timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' keycloak:8080/auth/realms/master)" != "200" ]]; do sleep 5; done' || false
    - name: Download and import Keycloak realm
      run: |
        curl -L -o realm.json https://raw.githubusercontent.com/ALTERNATIVE-EU/platform-deployment/master/deployment/charts/keycloak/realms/alternative-realm.json
        sed -i 's|url/|http://keycloak:8080/|g' realm.json
        docker exec keycloak /opt/bitnami/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password password
        docker exec keycloak /opt/bitnami/keycloak/bin/kcadm.sh create realms -f /realm.json
    - name: Setup extension
      run: |
        ckan -c test.ini db init
    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.keycloak_auth --disable-warnings ckanext/keycloak_auth