name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: openknowledge/ckan-dev:2.9
    services:
      solr:
        image: ckan/ckan-solr:2.9-solr8
      postgres:
        image: ckan/ckan-postgres-dev:2.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3
      keycloak:
        image: bitnami/keycloak:21
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: password
          KEYCLOAK_DATABASE_VENDOR: dev-file
        options: --health-cmd 'curl -f http://localhost:8080/auth/realms/master' --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 8080:8080
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      KEYCLOAK_URL: http://keycloak:8080/auth

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install -e .
    - name: Install Java
      run: |
        apk update
        apk add openjdk11-jdk
    - name: Download and import Keycloak realm
      run: |
        curl -L -o realm.json https://raw.githubusercontent.com/ALTERNATIVE-EU/platform-deployment/master/deployment/charts/keycloak/realms/alternative-realm.json
        sed -i 's|url/|http://keycloak:8080/|g' realm.json
        curl -L https://github.com/keycloak/keycloak/releases/download/16.1.1/keycloak-16.1.1.zip -o keycloak.zip
        unzip keycloak.zip
        ./keycloak-16.1.1/bin/kcadm.sh config credentials --server http://keycloak:8080/auth --realm master --user admin --password password
        ./keycloak-16.1.1/bin/kcadm.sh create realms -f realm.json
    - name: Setup extension
      run: |
        ckan -c test.ini db init
    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.keycloak_auth --disable-warnings ckanext/keycloak_auth
